# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 20:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_yn', models.NullBooleanField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('end_time', models.CharField(max_length=50, null=True)),
                ('entry_order', models.CharField(max_length=50, null=True)),
                ('is_deleted', models.NullBooleanField()),
                ('listing_mui', models.BigIntegerField(null=True)),
                ('matrix_modified_dt', models.DateTimeField(null=True)),
                ('matrix_unique_id', models.CharField(max_length=30, null=True)),
                ('open_house_date', models.DateTimeField(null=True)),
                ('open_house_type', models.CharField(max_length=50, null=True)),
                ('provider_key', models.CharField(max_length=200, null=True)),
                ('refreshments', models.CharField(max_length=5, null=True)),
                ('start_time', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='listing_mui',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='room_dimension',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='room_type',
        ),
        migrations.AddField(
            model_name='agent',
            name='member_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_internet_display',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_level',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code_plus4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state_or_province',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='matrix_modified_dt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='matrix_unique_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='web_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
