# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0005_auto_20171201_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.Property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'boards',
            },
        ),
        migrations.CreateModel(
            name='FavProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.Property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'favproperties',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favproperty',
            unique_together=set([('user', 'property')]),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('name', 'property')]),
        ),
    ]
