# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_auto_20180418_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_count', models.IntegerField(default=0)),
                ('mon_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tues_count', models.IntegerField(default=0)),
                ('tues_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wed_count', models.IntegerField(default=0)),
                ('wed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thurs_count', models.IntegerField(default=0)),
                ('thurs_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fri_count', models.IntegerField(default=0)),
                ('fri_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sat_count', models.IntegerField(default=0)),
                ('sat_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sun_count', models.IntegerField(default=0)),
                ('sun_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('weekly_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyviewcount',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='real_estate.Property'),
        ),
    ]
