from django.conf import settings
from django.db import models


# Create your models here.
class Hazard(models.Model):
    BEGIN_YEARMONTH = models.IntegerField(null=True)
    BEGIN_DAY = models.IntegerField(null=True)
    BEGIN_TIME = models.IntegerField(null=True)
    END_YEARMONTH = models.IntegerField(null=True)
    END_DAY = models.IntegerField(null=True)
    END_TIME = models.IntegerField(null=True)
    EPISODE_ID = models.IntegerField(null=True)
    EVENT_ID = models.IntegerField(null=True)
    STATE = models.CharField(max_length=200,null=True)
    STATE_FIPS = models.IntegerField(null=True)
    YEAR = models.IntegerField(null=True)
    MONTH_NAME = models.CharField(max_length=200,null=True)
    EVENT_TYPE = models.CharField(max_length=200,null=True)
    CZ_TYPE =   models.CharField(max_length=200,null=True)
    CZ_FIPS = models.IntegerField(null=True)
    CZ_NAME = models.CharField(max_length=200,null=True)
    WFO = models.CharField(max_length=200, null=True)
    BEGIN_DATE_TIME = models.DateTimeField(null=True)
    CZ_TIMEZONE = models.CharField(max_length=200, null=True)
    END_DATE_TIME = models.DateTimeField(null=True)
    INJURIES_DIRECT = models.IntegerField(null=True)
    INJURIES_INDIRECT = models.IntegerField(null=True)
    DEATHS_DIRECT = models.IntegerField(null=True)
    DEATHS_INDIRECT =  models.IntegerField(null=True)
    DAMAGE_PROPERTY = models.CharField(max_length=200, null=True)
    DAMAGE_CROPS = models.CharField(max_length=200, null=True)
    SOURCE = models.CharField(max_length=200, null=True)
    MAGNITUDE = models.FloatField(null=True)
    MAGNITUDE_TYPE = models.CharField(max_length=200, null=True)
    FLOOD_CAUSE = models.CharField(max_length=200, null=True)
    CATEGORY = models.CharField(max_length=200, null=True)
    TOR_F_SCALE =  models.CharField(max_length=200,null=True)
    TOR_LENGTH = models.FloatField(null=True)
    TOR_WIDTH = models.FloatField(null=True)
    TOR_OTHER_WFO = models.CharField(max_length=200, null=True)
    TOR_OTHER_CZ_STATE = models.CharField(max_length=200, null=True)
    TOR_OTHER_CZ_FIPS = models.CharField(max_length=200, null=True)
    TOR_OTHER_CZ_NAME = models.CharField(max_length=200, null=True)
    BEGIN_RANGE = models.IntegerField(null=True)
    BEGIN_AZIMUTH = models.CharField(max_length=200, null=True)
    BEGIN_LOCATION =  models.CharField(max_length=200, null=True)
    END_RANGE = models.IntegerField(null=True)
    END_AZIMUTH = models.CharField(max_length=200, null=True)
    END_LOCATION = models.CharField(max_length=200, null=True)
    BEGIN_LAT = models.DecimalField(max_digits=100, decimal_places=6, null = True)
    BEGIN_LON = models.DecimalField(max_digits=100, decimal_places=6, null=True)
    END_LAT = models.DecimalField(max_digits=100, decimal_places=6, null=True)
    END_LON = models.DecimalField(max_digits=100, decimal_places=6, null=True)
    EPISODE_NARRATIVE = models.CharField(max_length=50000, null=True)
    EVENT_NARRATIVE = models.CharField(max_length=50000, null=True)
    DATA_SOURCE =  models.CharField(max_length=200, null=True)

    def __str__(self):
      return self.EVENT_TYPE
