# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('institution_name', models.CharField(max_length=80, null=True)),
                ('street_address', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('grade_levels', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('total_students', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
            ],
        ),
    ]
