# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_api_key', models.CharField(default='AIzaSyCHa5mFbTGgyAABDm_d7M4msCk1LoF53tk', max_length=200)),
                ('polr_duration_max_tolerance', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('polr_search_angles', models.IntegerField(default=15)),
                ('polr_search_iterations', models.IntegerField(default=32)),
                ('polr_max_mpm', models.DecimalField(decimal_places=2, default=1.25, max_digits=5)),
                ('polr_google_matrix_elements_ps', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=200, unique=True)),
                ('color_1', models.CharField(max_length=7)),
                ('color_2', models.CharField(max_length=7)),
                ('color_3', models.CharField(max_length=7)),
                ('color_4', models.CharField(max_length=7)),
                ('color_5', models.CharField(max_length=7)),
                ('color_6', models.CharField(max_length=7)),
                ('image', models.CharField(max_length=50)),
                ('brand_font', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='system_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.Themes'),
        ),
    ]
