# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-30 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('trashed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='default_tab',
            field=models.IntegerField(default=1),
        ),
    ]
