# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20180330_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfilter',
            name='locations',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyfilter',
            name='condition',
            field=models.CharField(max_length=500),
        ),
    ]
