# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BEGIN_YEARMONTH', models.IntegerField(null=True)),
                ('BEGIN_DAY', models.IntegerField(null=True)),
                ('BEGIN_TIME', models.IntegerField(null=True)),
                ('END_YEARMONTH', models.IntegerField(null=True)),
                ('END_DAY', models.IntegerField(null=True)),
                ('END_TIME', models.IntegerField(null=True)),
                ('EPISODE_ID', models.IntegerField(null=True)),
                ('EVENT_ID', models.IntegerField(null=True)),
                ('STATE', models.CharField(max_length=200, null=True)),
                ('STATE_FIPS', models.IntegerField(null=True)),
                ('YEAR', models.IntegerField(null=True)),
                ('MONTH_NAME', models.CharField(max_length=200, null=True)),
                ('EVENT_TYPE', models.CharField(max_length=200, null=True)),
                ('CZ_TYPE', models.CharField(max_length=200, null=True)),
                ('CZ_FIPS', models.IntegerField(null=True)),
                ('CZ_NAME', models.CharField(max_length=200, null=True)),
                ('WFO', models.CharField(max_length=200, null=True)),
                ('BEGIN_DATE_TIME', models.DateTimeField(null=True)),
                ('CZ_TIMEZONE', models.CharField(max_length=200, null=True)),
                ('END_DATE_TIME', models.DateTimeField(null=True)),
                ('INJURIES_DIRECT', models.IntegerField(null=True)),
                ('INJURIES_INDIRECT', models.IntegerField(null=True)),
                ('DEATHS_DIRECT', models.IntegerField(null=True)),
                ('DEATHS_INDIRECT', models.IntegerField(null=True)),
                ('DAMAGE_PROPERTY', models.CharField(max_length=200, null=True)),
                ('DAMAGE_CROPS', models.CharField(max_length=200, null=True)),
                ('SOURCE', models.CharField(max_length=200, null=True)),
                ('MAGNITUDE', models.FloatField(null=True)),
                ('MAGNITUDE_TYPE', models.CharField(max_length=50, null=True)),
                ('FLOOD_CAUSE', models.CharField(max_length=200, null=True)),
                ('CATEGORY', models.CharField(max_length=200, null=True)),
                ('TOR_F_SCALE', models.FloatField(null=True)),
                ('TOR_LENGTH', models.FloatField(null=True)),
                ('TOR_WIDTH', models.FloatField(null=True)),
                ('TOR_OTHER_WFO', models.CharField(max_length=200, null=True)),
                ('TOR_OTHER_CZ_STATE', models.CharField(max_length=200, null=True)),
                ('TOR_OTHER_CZ_FIPS', models.CharField(max_length=200, null=True)),
                ('TOR_OTHER_CZ_NAME', models.CharField(max_length=200, null=True)),
                ('BEGIN_RANGE', models.IntegerField(null=True)),
                ('BEGIN_AZIMUTH', models.CharField(max_length=200, null=True)),
                ('BEGIN_LOCATION', models.CharField(max_length=200, null=True)),
                ('END_RANGE', models.IntegerField(null=True)),
                ('END_AZIMUTH', models.CharField(max_length=200, null=True)),
                ('END_LOCATION', models.CharField(max_length=200, null=True)),
                ('BEGIN_LAT', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('BEGIN_LON', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('END_LAT', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('END_LON', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('EPISODE_NARRATIVE', models.CharField(max_length=50, null=True)),
                ('EVENT_NARRATIVE', models.CharField(max_length=50, null=True)),
                ('DATA_SOURCE', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
