# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_auto_20171103_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='BEGIN_LAT',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='BEGIN_LON',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='DATA_SOURCE',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='END_LAT',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='END_LON',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='EPISODE_NARRATIVE',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='EVENT_NARRATIVE',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='MAGNITUDE_TYPE',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='TOR_F_SCALE',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
