# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfn_number', models.CharField(blank=True, max_length=4, null=True)),
                ('cfn_sequence', models.CharField(blank=True, max_length=10, null=True)),
                ('group_id', models.CharField(blank=True, max_length=5, null=True)),
                ('recording_date', models.CharField(blank=True, max_length=8, null=True)),
                ('recording_time', models.CharField(blank=True, max_length=6, null=True)),
                ('recording_book', models.CharField(blank=True, max_length=14, null=True)),
                ('recording_page', models.CharField(blank=True, max_length=5, null=True)),
                ('book_type', models.CharField(blank=True, max_length=5, null=True)),
                ('document_pages', models.CharField(blank=True, max_length=5, null=True)),
                ('append_pages', models.CharField(blank=True, max_length=5, null=True)),
                ('document_type', models.CharField(blank=True, max_length=15, null=True)),
                ('document_type_description', models.CharField(blank=True, max_length=40, null=True)),
                ('document_date', models.CharField(blank=True, max_length=8, null=True)),
                ('first_party', models.CharField(blank=True, max_length=100, null=True)),
                ('first_party_code', models.CharField(blank=True, max_length=1, null=True)),
                ('cross_party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('original_cfn_year', models.CharField(blank=True, max_length=4, null=True)),
                ('original_cfn_sequence', models.CharField(blank=True, max_length=10, null=True)),
                ('original_recording_book', models.CharField(blank=True, max_length=14, null=True)),
                ('original_recording_page', models.CharField(blank=True, max_length=5, null=True)),
                ('original_misc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('subdivision_name', models.CharField(blank=True, max_length=90, null=True)),
                ('folio_number', models.CharField(blank=True, max_length=15, null=True)),
                ('legal_description', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('township', models.CharField(blank=True, max_length=5, null=True)),
                ('range', models.CharField(blank=True, max_length=5, null=True)),
                ('plat_book', models.CharField(blank=True, max_length=14, null=True)),
                ('plat_page', models.CharField(blank=True, max_length=5, null=True)),
                ('block', models.CharField(blank=True, max_length=20, null=True)),
                ('case_number', models.CharField(blank=True, max_length=30, null=True)),
                ('consideration_one', models.CharField(blank=True, max_length=20, null=True)),
                ('consideration_two', models.CharField(blank=True, max_length=20, null=True)),
                ('deed_doc_tax', models.CharField(blank=True, max_length=20, null=True)),
                ('single_family', models.CharField(blank=True, max_length=20, null=True)),
                ('surtax', models.CharField(blank=True, max_length=20, null=True)),
                ('intangible', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_stamps', models.CharField(blank=True, max_length=20, null=True)),
                ('key', models.CharField(blank=True, max_length=13, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=2, null=True)),
                ('party_sequence', models.CharField(blank=True, max_length=8, null=True)),
                ('modified_date', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LienRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfn_number', models.CharField(blank=True, max_length=4, null=True)),
                ('cfn_sequence', models.CharField(blank=True, max_length=10, null=True)),
                ('group_id', models.CharField(blank=True, max_length=5, null=True)),
                ('recording_date', models.CharField(blank=True, max_length=8, null=True)),
                ('recording_time', models.CharField(blank=True, max_length=6, null=True)),
                ('recording_book', models.CharField(blank=True, max_length=14, null=True)),
                ('recording_page', models.CharField(blank=True, max_length=5, null=True)),
                ('book_type', models.CharField(blank=True, max_length=5, null=True)),
                ('document_pages', models.CharField(blank=True, max_length=5, null=True)),
                ('append_pages', models.CharField(blank=True, max_length=5, null=True)),
                ('document_type_description', models.CharField(blank=True, max_length=40, null=True)),
                ('document_date', models.CharField(blank=True, max_length=8, null=True)),
                ('first_party', models.CharField(blank=True, max_length=100, null=True)),
                ('first_party_code', models.CharField(blank=True, max_length=1, null=True)),
                ('cross_party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.CharField(blank=True, max_length=8, null=True)),
                ('folio_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
