# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180209_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_theme',
        ),
    ]
