# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_user_theme'),
        ('user', '0005_auto_20180412_0939'),
    ]

    operations = [
    ]
